# Generated by Django 3.2.16 on 2022-12-07 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
    ]
