# Generated by Django 3.2.16 on 2022-12-12 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_rename_cart_cart_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='val',
            field=models.FloatField(default=0.0),
        ),
    ]
