# Generated by Django 3.2.16 on 2022-12-14 17:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cart', '0003_alter_cart_val'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='val',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='client',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='product',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='val',
        ),
        migrations.AddField(
            model_name='cart',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='authentication.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchase',
            name='content',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='cart.cart'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchase',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
