# Generated by Django 3.2.16 on 2022-12-19 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_auto_20221214_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='content',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.DO_NOTHING, to='cart.cart'),
        ),
    ]
